### PR TITLE
Add new file extension suffixes to naming conventions guide

### PR DESCRIPTION
**Pull request by denniskigen**
This update adds information about three file type suffixes:

- `*.modal.tsx` for modals
- `*.extension.tsx` for extensions
- `*.workspace.tsx` for workspace forms

### CODE REVIEW

**Review by NethmiRodrigo — APPROVED** [review]
LGTM, thanks @denniskigen!

**Comment by brandones** [comment]
Why `*.modal.component.tsx` and not `*.modal.tsx` ?

**Comment by denniskigen** [comment]
> Why `*.modal.component.tsx` and not `*.modal.tsx` ?

I could only find one occurrence of `modal.tsx` in Core, for example. It looks like we're not super consistent about that one pattern, or that the other custom extensions are more prevalent in our codebase. Either way, happy to change it to `modal.tsx`, but that'll require refactoring various files to match the new convention.

**Comment by brandones** [comment]
Yeah let's do `modal.tsx` and refactor :)

I think it would be awesome to have a consistent norm that each top-level element in the `routes` file has its own file extension, `[whateveritis].tsx`. And then `component.tsx` is anything that isn't loaded via the routes file.

**Comment by ibacher** [comment]
I love @brandones suggestion!

**Comment by denniskigen** [comment]
Refactor is done everywhere, I think. I'm proceeding to merge this in.

**Pull request merged**
